import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Link from "next/dist/client/link";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
        <nav className="border-b bg-white px-6 py-4 flex gap-6 items-center">
          <span className="font-bold text-lg">Teams Tracking</span>
          <Link href="/agents" className="text-sm hover:underline">Agentes</Link>
          <Link href="/map" className="text-sm hover:underline">Mapa</Link>
          <Link href="/check-ins" className="text-sm hover:underline">Check-ins</Link>
          <Link href="/sync" className="text-sm hover:underline">Sincronização</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
