spring.application.name=backend

# Banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/teams_tracking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:tracker}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:tracker123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Servidor
server.port=8080

# Forçar modo servlet (não reativo)
spring.main.web-application-type=servlet

# GPS API CLIENT
gps.api.base-url=${GPS_API_BASE_URL:https://desafio-media.onrender.com}
gps.api.key=${GPS_API_KEY:m4a_9d7f2c1ab84e6f03b2c91d5aa77e4c6f8b1d2e3f4a5b6c7}